export const LATEST_MOVIE_REQUEST = "LATEST_MOVIE_REQUEST";
export const LATEST_MOVIE_SUCCESS = "LATEST_MOVIE_SUCCESS";
export const LATEST_MOVIE_FAIL = "LATEST_MOVIE_FAIL";
export const LATEST_MOVIE_RESET = "LATEST_MOVIE_RESET";

export const TRENDING_ITEM_REQUEST = "TRENDING_ITEM_REQUEST";
export const TRENDING_ITEM_SUCCESS = "TRENDING_ITEM_SUCCESS";
export const TRENDING_ITEM_FAIL = "TRENDING_ITEM_FAIL";

export const PLAYING_MOVIE_REQUEST = "PLAYING_MOVIE_REQUEST";
export const PLAYING_MOVIE_SUCCESS = "PLAYING_MOVIE_SUCCESS";
export const PLAYING_MOVIE_FAIL = "PLAYING_MOVIE_FAIL";
export const PLAYING_MOVIE_RESET = "PLAYING_MOVIE_RESET";

export const TRENDING_MOVIE_REQUEST = "TRENDING_MOVIE_REQUEST";
export const TRENDING_MOVIE_SUCCESS = "TRENDING_MOVIE_SUCCESS";
export const TRENDING_MOVIE_FAIL = "TRENDING_MOVIE_FAIL";

export const DISCOVER_MOVIE_REQUEST = "DISCOVER_MOVIE_REQUEST";
export const DISCOVER_MOVIE_SUCCESS = "DISCOVER_MOVIE_SUCCESS";
export const DISCOVER_MOVIE_FAIL = "DISCOVER_MOVIE_FAIL";

export const UPCOMMING_MOVIE_REQUEST = "UPCOMMING_MOVIE_REQUEST";
export const UPCOMMING_MOVIE_SUCCESS = "UPCOMMING_MOVIE_SUCCESS";
export const UPCOMMING_MOVIE_FAIL = "UPCOMMING_MOVIE_FAIL";

export const TOPRATED_MOVIE_REQUEST = "TOPRATED_MOVIE_REQUEST";
export const TOPRATED_MOVIE_SUCCESS = "TOPRATED_MOVIE_SUCCESS";
export const TOPRATED_MOVIE_FAIL = "TOPRATED_MOVIE_FAIL";

export const INDIVIDUAL_MOVIE_REQUEST = "INDIVIDUAL_MOVIE_REQUEST";
export const INDIVIDUAL_MOVIE_SUCCESS = "INDIVIDUAL_MOVIE_SUCCESS";
export const INDIVIDUAL_MOVIE_FAIL = "INDIVIDUAL_MOVIE_FAIL";

export const MOVIE_CAST_REQUEST = "MOVIE_CAST_REQUEST";
export const MOVIE_CAST_SUCCESS = "MOVIE_CAST_SUCCESS";
export const MOVIE_CAST_FAIL = "MOVIE_CAST_FAIL";

export const MOVIE_REVIEW_REQUEST = "MOVIE_REVIEW_REQUEST";
export const MOVIE_REVIEW_SUCCESS = "MOVIE_REVIEW_SUCCESS";
export const MOVIE_REVIEW_FAIL = "MOVIE_REVIEW_FAIL";

export const MOVIE_RECOMMENDATION_REQUEST = "MOVIE_RECOMMENDATION_REQUEST";
export const MOVIE_RECOMMENDATION_SUCCESS = "MOVIE_RECOMMENDATION_SUCCESS";
export const MOVIE_RECOMMENDATION_FAIL = "MOVIE_RECOMMENDATION_FAIL";

export const MOVIE_SIMILAR_REQUEST = "MOVIE_SIMILAR_REQUEST";
export const MOVIE_SIMILAR_SUCCESS = "MOVIE_SIMILAR_SUCCESS";
export const MOVIE_SIMILAR_FAIL = "MOVIE_SIMILAR_FAIL";

export const MOVIE_VIDEOS_REQUEST = "MOVIE_VIDEOS_REQUEST";
export const MOVIE_VIDEOS_SUCCESS = "MOVIE_VIDEOS_SUCCESS";
export const MOVIE_VIDEOS_FAIL = "MOVIE_VIDEOS_FAIL";
