export const PEOPLE_REQUEST = "PEOPLE_REQUEST";
export const PEOPLE_SUCCESS = "PEOPLE_SUCCESS";
export const PEOPLE_FAIL = "PEOPLE_FAIL";
export const PEOPLE_RESET = "PEOPLE_RESET";

export const PEOPLE_DETAILS_REQUEST = "PEOPLE_DETAILS_REQUEST";
export const PEOPLE_DETAILS_SUCCESS = "PEOPLE_DETAILS_SUCCESS";
export const PEOPLE_DETAILS_FAIL = "PEOPLE_DETAILS_FAIL";

export const PEOPLE_MOVIE_REQUEST = "PEOPLE_MOVIE_REQUEST";
export const PEOPLE_MOVIE_SUCCESS = "PEOPLE_MOVIE_SUCCESS";
export const PEOPLE_MOVIE_FAIL = "PEOPLE_MOVIE_FAIL";

export const PEOPLE_TV_REQUEST = "PEOPLE_TV_REQUEST";
export const PEOPLE_TV_SUCCESS = "PEOPLE_TV_SUCCESS";
export const PEOPLE_TV_FAIL = "PEOPLE_TV_FAIL";
