export const LATEST_TV_REQUEST = "LATEST_TV_REQUEST";
export const LATEST_TV_SUCCESS = "LATEST_TV_SUCCESS";
export const LATEST_TV_FAIL = "LATEST_TV_FAIL";
export const LATEST_TV_RESET = "LATEST_TV_RESET";

export const DISCOVER_TV_REQUEST = "DISCOVER_TV_REQUEST";
export const DISCOVER_TV_SUCCESS = "DISCOVER_MOVIE_SUCCESS";
export const DISCOVER_TV_FAIL = "DISCOVER_MOVIE_FAIL";

export const AIRING_TODAY_TV_REQUEST = "AIRING_TODAY_TV_REQUEST";
export const AIRING_TODAY_TV_SUCCESS = "AIRING_TODAY_TV_SUCCESS";
export const AIRING_TODAY_TV_FAIL = "AIRING_TODAY_TV_FAIL";

export const ON_TV_REQUEST = "ON_TV_REQUEST";
export const ON_TV_SUCCESS = "ON_TV_SUCCESS";
export const ON_TV_FAIL = "ON_TV_FAIL";

export const INDIVIDUAL_TV_REQUEST = "INDIVIDUAL_TV_REQUEST";
export const INDIVIDUAL_TV_SUCCESS = "INDIVIDUAL_TV_SUCCESS";
export const INDIVIDUAL_TV_FAIL = "INDIVIDUAL_TV_FAIL";

export const TV_CAST_REQUEST = "TV_CAST_REQUEST";
export const TV_CAST_SUCCESS = "TV_CAST_SUCCESS";
export const TV_CAST_FAIL = "TV_CAST_FAIL";

export const TV_VIDEOS_REQUEST = "TV_VIDEOS_REQUEST";
export const TV_VIDEOS_SUCCESS = "TV_VIDEOS_SUCCESS";
export const TV_VIDEOS_FAIL = "TV_VIDEOS_FAIL";

export const TV_RECOMMENDATION_REQUEST = "TV_RECOMMENDATION_REQUEST";
export const TV_RECOMMENDATION_SUCCESS = "TV_RECOMMENDATION_SUCCESS";
export const TV_RECOMMENDATION_FAIL = "TV_RECOMMENDATION_FAIL";

export const TV_SIMILAR_REQUEST = "TV_SIMILAR_REQUEST";
export const TV_SIMILAR_SUCCESS = "TV_SIMILAR_SUCCESS";
export const TV_SIMILAR_FAIL = "TV_SIMILAR_FAIL";

export const TV_REVIEW_REQUEST = "TV_REVIEW_REQUEST";
export const TV_REVIEW_SUCCESS = "TV_REVIEW_SUCCESS";
export const TV_REVIEW_FAIL = "TV_REVIEW_FAIL";
